<a href="https://colab.research.google.com/github/KababDoesGitHub/Colab-Repo-Python-AI/blob/main/Tensorflow_%26_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import keras

In [5]:
const_1 = tf.constant(100)

In [6]:
const_1.shape

TensorShape([])

In [7]:
const_1.numpy()

100

In [8]:
const_2 = tf.constant([10, 20 , 30, 40, 50, 60, 70, 80])

In [11]:
const_2.shape

TensorShape([8])

In [12]:
const_2.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(8,), dtype=int32, numpy=array([10, 20, 30, 40, 50, 60, 70, 80], dtype=int32)>>

In [16]:
const_3 = tf.constant([[10, 20 , 30, 40, 50, 60, 70, 80],[10, 20 , 30, 40, 50, 60, 70, 80],[10, 20 , 30, 40, 50, 60, 70, 80]])

In [17]:
const_3.shape

TensorShape([3, 8])

In [19]:
const_3.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[10, 20, 30, 40, 50, 60, 70, 80],
       [10, 20, 30, 40, 50, 60, 70, 80],
       [10, 20, 30, 40, 50, 60, 70, 80]], dtype=int32)>>

In [20]:
const_4 = tf.constant([[[10, 20 , 30, 40, 50, 60, 70, 80],[10, 20 , 30, 40, 50, 60, 70, 80],[10, 20 , 30, 40, 50, 60, 70, 80]],[[10, 20 , 30, 40, 50, 60, 70, 80],[10, 20 , 30, 40, 50, 60, 70, 80],[10, 20 , 30, 40, 50, 60, 70, 80]]])

In [21]:
const_4.shape

TensorShape([2, 3, 8])

In [22]:
const_4.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 3, 8), dtype=int32, numpy=
array([[[10, 20, 30, 40, 50, 60, 70, 80],
        [10, 20, 30, 40, 50, 60, 70, 80],
        [10, 20, 30, 40, 50, 60, 70, 80]],

       [[10, 20, 30, 40, 50, 60, 70, 80],
        [10, 20, 30, 40, 50, 60, 70, 80],
        [10, 20, 30, 40, 50, 60, 70, 80]]], dtype=int32)>>

Mathematical Operations

In [27]:
X = tf.constant([[8],[9],[11],[10],[12]])

In [28]:
X.shape

TensorShape([5, 1])

In [33]:
W = tf.Variable([[10],[11],[12],[13],[14]])

In [35]:
WT = tf.transpose(W)

In [36]:
tf.tensordot(WT,X, axes = 1)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[609]], dtype=int32)>

Keras is high level API based on Tensorflow, to create Deep Learning Neural Networks easily. Dense Neural Netowrk(DNN), Convoluted Neural Network (CNN), Recurrent Neural Network(RNN)